### ISSUE TITLE
Migrate from Travis to GitHub Actions

### ISSUE THREAD

**Issue by colekettler** [azavea/raster-vision#1129]
We've been moving away from using Travis for CI across the organization. We've been investing heavily in GitHub Actions instead. We should migrate this repository to use Actions for CI and building Docker images.

Required by #1130.

**Comment by lewfish** [comment]
I'd like to bump this up in priority if possible since this repo effectively has no CI now. The build pages say "Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on." We can migrate to travis-ci.com as a stop gap, but it probably makes more sense to switch straight to Github actions. I haven't used Github actions before, but I could do it myself if there's a good example to follow. Or I can let the Ops team do it if that's easier.

**Comment by colekettler** [comment]
@lewfish Thanks for calling this out! We've added it to our upcoming sprint.

**Comment by lewfish** [comment]
> @lewfish Thanks for calling this out! We've added it to our upcoming sprint.

Thank you!
