### ISSUE TITLE
Chip size range

### ISSUE THREAD

**Issue by sagar1899** [azavea/raster-vision#1278]
Currently I have 16 gb ram and chip size is 1000.
Training dataset contains total 1200 chips of size 1000*1000.
And I'm getting memory error.

Unable to allocate 9 gb ram buy a new RAM. Like that

So can you mention chip size range of maximum size of chip?

**Comment by jamesmcclain** [comment]
If you find that a particular chip size causes you to run out of GPU memory, you can try to compensate by reducing the batch size.  It is not easy for us to give you an exact formula to compute the maximum chip size for your project because that is dependent on many particular factors that we do not have knowledge of.
