### ISSUE TITLE
FileSystem plugin for Azure Blob Storage

### ISSUE THREAD

**Issue by theoway** [azavea/raster-vision#1340]
## 🚀 Feature
Adding integration of Azure Blob Storage for File I/O, just like there is for AWS S3.

## Motivation

Azure blob storage is quite popular and widely used. Rastervision lacks the support for it. Also, my personal project uses Azure blob storage, so I'd love to have Azure storage integration

## Pitch

User should be able to add a flag and pass Azure Storage credentials(like they do for AWS S3) so that whenever they execute run/predict etc. commands, the files are read from and stored to given Blob Storage.

## Alternatives

No alternatives are there.

## Additional context

I've been working with Azure components for quite some time and **would love to contribute**. My current plan of action:
- Create a new plugin for _Blob Storage_
- Extend a new subclass from the base class `FileSystem`

Now from here, I don't know how to integrate this new class with the core. Or how the user can set a flag/add parameter to a run/predict command so that it uses this **plugin** for File I/O

**Comment by jamesmcclain** [comment]
Hello, Raster Vision currently has a backend that uses [GDAL's VSI filesystem](https://gdal.org/user/virtual_file_systems.html) to do reads, so it is possible to read from Azure blob storage using that mechanism.  I believe that writing should work as well, though I am not sure if that is as well-tested as reading.  One can use this mechanism by passing a valid GDAL VSI URI to raster vision (e.g. instead of `/home/user/my-image.tif` or `s3://my-bucket/my-image.tif`, something like `/vsis3/my-bucket/my-image.tif` or even `/vsitar//vsis3/my-bucket/my-archive.tar/my-image.tif`).

Please see the link given above for more information about GDAL's VSI capabiltiy.

**Comment by theoway** [comment]
@jamesmcclain Thank you so much for such a comprehensive answer! I'll do some experimenting and update you how it goes! 😄

**Comment by jamesmcclain** [comment]
> @jamesmcclain Thank you so much for such a comprehensive answer! I'll do some experimenting and update you how it goes! smile

You are most welcome, please let me know if I can be of further service.

**Comment by theoway** [comment]
> You are most welcome, please let me know if I can be of further service.
>
 Sure! I'll check if files can be read and written to Azure storage with GDAL VSI. Upon success, we can close this issue.

**Comment by theoway** [comment]
It works well. One just has to provide Azure credentials beforehand. [Here](https://gdal.org/user/configoptions.html) it is shown how to configure credentials for GDAL. Closing this issue.

**Comment by jamesmcclain** [comment]
> It works well. One just has to provide Azure credentials beforehand. [Here](https://gdal.org/user/configoptions.html) it is shown how to configure credentials for GDAL. Closing this issue.

Nice, I'm glad that it worked for you!
