### ISSUE TITLE
Makefile error when `root_uri` is an S3 path

### ISSUE THREAD

**Issue by theoway** [azavea/raster-vision#1452]
## 🐛 Bug
When running training command and having `root_uri` set to an S3 folder, this error shows up:
```
make: s3://<random_bucket_name>/predictions/Makefile: No such file or directory
make: *** No rule to make target 's3://<random_bucket_name>/predictions/Makefile'.  Stop.
```

This error disappears when `root_uri` is a local path. AWS config is right as it is able to read and write the files.

## To Reproduce

1. I ran the following command inside the container:
`python -m rastervision.pipeline.cli run local code/local_exp.py -a raw_uri s3://<random_bucket_name>/datafortesting/data/ -a root_uri s3://<random_bucket_name>/predictions -a test False`

## Expected behavior

It should run normally like it is running when `root_uri` is a local path.

## Environment

Running with docker.  **Image**: quay.io/azavea/raster-vision:pytorch-v0.13.1

## Additional context

This might be a relevant issue: #991

**Comment by AdeelH** [comment]
Yes, this is the same as #991.

Two possible workarounds:
1. Use `inprocess` instead of `local`: `python -m rastervision.pipeline.cli run inprocess ...`
2. Change this line so that `makefile_path` is a local path (e.g. in a temporary directory): https://github.com/azavea/raster-vision/blob/b735cffe76b2918a48cfe26b2f8047626716ec65/rastervision_pipeline/rastervision/pipeline/runner/local_runner.py#L69

**Comment by theoway** [comment]
Will this error still occur if use `batch` in the run command?

**Comment by AdeelH** [comment]
No. This is specific to `local`.
