### ISSUE TITLE
Unable to install RasterVision

### ISSUE THREAD

**Issue by zejian99** [azavea/raster-vision#1868]
## 🐛 Bug

I was trying to install RasterVision version 0.21, and I encountered this issue

![image](https://github.com/azavea/raster-vision/assets/100704949/2ac8171b-ba76-4cbe-b7f2-52d18ebb6513)

## To Reproduce

1. I created a new conda python 3.10 environment
2. Ran `pip install rastervision==0.21`
3. Hit the error

## Environment

 - Raster Vision version or commit: 0.21
 - OS (e.g., Linux): macOS 13.4.1 
 - Python version: 3.10.9

**Comment by AdeelH** [comment]
Hmm, I am not able to reproduce this. Can you tell me which package in particular is causing this? You should be able to tell from the stack trace.

**Comment by zejian99** [comment]
![image](https://github.com/azavea/raster-vision/assets/100704949/12f4bb39-318d-42dd-852f-9c5a5e3026da)
![image](https://github.com/azavea/raster-vision/assets/100704949/39189ada-f452-41e7-9ebc-f48894510068)


These are the screenshots, I'm not sure how to fix this issue.

**Comment by AdeelH** [comment]
You seem to be running into https://github.com/yaml/pyyaml/issues/724. But this shouldn't happen since this was supposedly [fixed](https://github.com/yaml/pyyaml/issues/724#issuecomment-1641571578) in https://github.com/azavea/raster-vision/commit/2c3748fb283e6091584df06d0e337df58af963cf.

It is also strange that pip is trying to install pyyaml==5.4.1 instead of the latest version because the pyyaml dependency comes from albumentations and it [doesn't specify any constraints on the pyyaml version](https://github.com/albumentations-team/albumentations/blob/2a857a8c8cb604f95729b387c465f0dd26ef560a/setup.py#L8).

You can try running `pip install pyyaml==6.0.1` before you try installing Raster Vision. If that doesn't work, consider attempting the install in a fresh conda/python environment.
