### ISSUE TITLE
onnx_inference.ipynb raises No module named 'onnxruntime'

### ISSUE THREAD

**Issue by robmarkcole** [azavea/raster-vision#2214]
As title

**Comment by robmarkcole** [comment]
There is also a typo: `Vsiualize`

**Comment by AdeelH** [comment]
Yeah, the notebook should discuss the installation of onnxruntime. We do not include it as a dependency because installation can vary by hardware. This is how it's installed in the Raster Vision docker image: https://github.com/azavea/raster-vision/blob/b263422310e5ece8dab3c9a9f1f1dbf5fce5a46d/Dockerfile#L193-L194

**Comment by robmarkcole** [comment]
Suggest linking to the onnx docs - I did go through this process recently and it wasn't too straightforward on GPU :-)

**Comment by AdeelH** [comment]
Fixed in #2215
