### ISSUE TITLE
Rework/Clean up the way we set the temporary directory to use

### ISSUE THREAD

**Issue by lossyrob** [azavea/raster-vision#400]
This block of code needs to be refactored into a proper place, and cleaned up a bit  to make it more clear exactly what it does. The temporary directory configuration should be a setting inside the raster vision configuration (rv_config) and also a command line argument (in the `main` method in `cli/main.py`

https://github.com/azavea/raster-vision/blob/develop/src/rastervision/utils/files.py#L298-L326

**Comment by lewfish** [comment]
I noticed in the refactor that you made it so `tmp_dir` is passed into a lot of functions. I think this is unnecessary because this line of code makes it so that all temp dirs created with `tempfile` are inside `RV_TEMP_DIR` https://github.com/azavea/raster-vision/blob/develop/src/rastervision/utils/files.py#L325
