### ISSUE TITLE
Implement predict-only backends

### ISSUE THREAD

**Issue by lossyrob** [azavea/raster-vision#405]
Implement in the architecture a predict-only backend. These will be a no-op for the analyze, chip and train commands, and do predict, eval and bundle. This will enable us to create backends that do ensembling, as well as make predictions and evaluate off of pre-existing prediction packages.

Architecture notes:
- Refactor Backend to derive from a `PredictBackend`
- Move predict code from `Backend` to `PredictBackend`
- In the `make_command` logic for an Experiment, check if the backend is a `Backend` - if not, return None for the analyze, chip and train commands. Handle that None at the call sites.

**Comment by lewfish** [comment]
I'm closing this because it's been open for a long time and there's no immediate need for it or plan to implement it. The new RV should make it easier to implement something like this as a one-off instance of a pipeline if it's needed for some reason which can later be incorporated into the library. Feel free to re-open if you desire.
