### ISSUE TITLE
Create Ensemble backend

### ISSUE THREAD

**Issue by lossyrob** [azavea/raster-vision#406]
Depends on #405 

Create a backend that is an ensemble of other models. The ConfigBuilder for this backend should make it easy to pass in other backends and experiments and get the model information from them. This is a predict-only backend, which will do predictions, evaluation, and also create a predict package, which will package up each of the ensembled models.

**Comment by lewfish** [comment]
I don't think we want to create an ensemble backend. I think it's simpler to just create an ensemble command that averages together a set of prediction files. That's what we did in the Kaggle contest. I can imagine a similar `concat-eval` command that takes the evals for a bunch of experiments and concatenates them to we can plot the results from all experiments. 

I think I agree that an ensemble backend would be useful if you actually wanted to deploy an ensembled model, but that doesn't seem like something we'd ever do in practice since ensembles are only used in contests.
