### ISSUE TITLE
Research computer vision libraries

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#471]
We'd like to create a new backend for one of the tasks using a user-friendly deep learning computer vision library. Research https://gluon-cv.mxnet.io/ and https://github.com/chainer/chainercv.
To see if this is generally a good idea and help make a decision about which library to use read documentation for the libraries and take some notes (bullet points are good). Especially pay attention to:
* installation process
* community around the library (issues, prs, etc)
* quality of documentation
* how to create a custom dataset
* how to configure a model/training
* how to train a model
* how to make predictions
* general impression of how flexible and elegant the API is
* the variety of models that are supported

**Comment by lewfish** [comment]
* the ability to resume training from a checkpoint
* generating log output while training to Tensorboard or similar

**Comment by nholeman** [comment]
My choice: **GluonCV**. Here's why:

*Comparison*

|                  | GluonCV | ChainerCV |
| :-------------: | ------------- | ----- |
| **Installation** | MXNet | numpy, chainer, pillow, cython <br> for extra funcionality: chainerMN, matplotlib, OpenCV, and SciPy |
| **Community** | Current version: 0.3.0<br>Last update: < 1 week ago<br>Popularity: 164 Forks, 896 Stars, 125k downloads<br>No. Contributors: 26<br>License: Apache-2.<br>active discussion forum | Current version: 0.10.0<br>Last update: < 1 week ago<br>Popularity: 179 Forks, 832 Stars<br>No. Contributors: 19<br>License: MIT. <no active discussion forum> |
| **Documentation** | Large, better organized than ChainerCV | Large, more in volume than GluonCV |
| **Custom Dataset** | Due to MXNet convention, recommended to use LST files, which are plain text list files to store labels.<br>Supports deriving from PASCAL VOC format | ChainerCV Experimental: GetterDataset |
| **Config Model/Training** | straight-forward | straight-forward |
| **Training** | training done with gluon.utils | training is done directly with Chainer |
| **Make Prediction** | Easy | Easy |
| **API Flexibility** | Supports image classification, object detection, and semantic segmentation, and instance segmentation | Supports image classification, object detection, semantic segmentation, and instance segmentation<br>ChainerCV's implementation was in an academic setting for a competition. As such, it seems to be less flexible overall than GluonCV, which is more of a developed product. |
| **Model Variety** | CIFAR: 10 models<br>ImageNet: 5 models<br>SSD: 11 models<br>FasterRCNN: 3 models<br>YOLOv3: 3 models<br>Mask RCNN: 1 model<br>FCN: 5 models<br>PSPNet: 4 models<br>DeepLabV3: 4 models | *Classification*:<br>VGG16<br>ResNet50<br>ResNet101<br>ResNet152<br>*Detection*:<br>Faster R-CNN<br>SSD300<br>SSD512<br>YOLOv2<br>YOLOv3<br>*Semantic Segmentation*:<br>SegNet<br>PSPNet |
| **CPU/GPU** | yes | yes |
| **Library Maturity** | project began Feb 2018 | began 2018 |
| **Stop/Resume training** | yes | no |
| **Log output** | yes | no |

**Other Thoughts**
GluonCV: GluonCV’s documentation is more organized and more production-ready than ChainerCV.
ChainerCV: Some useful modules in ChainerCV (like creating your own dataset) are WIPs for Chainer and will be removed from ChainerCV when they are fully developed. If any of these modules are used, Raster Vision will have to refactor once they are moved into Chainer.

**Conclusion**
Overall, ChainerCV was easier for me to get up and running. However, as I used these tools more, I became more convinced that GluonCV is better-equipped to be used in a flexible plugin for Raster Vision. GluonCV has better-organized documentation, more avenues for discussion (forum and GitHub issues), and features that won't be deprecated later (like Chainer's WIP modules that are currently ChainerCV features).

**Comment by lewfish** [comment]
GluonCV it is!
