### ISSUE TITLE
`validate` methods should check types

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#519]
Each ConfigBuilder class has a `validate` method that checks that various fields have been set. These should also check that the values are of the correct type. I forgot to call `build()` on a backend, and when I built the experiment (which depends on the backend), I got the following error which could be confusing to a new user.
```
File "/opt/src/rastervision/experiment/experiment_config.py", line 54, in update_for_command
  new_backend, sub_io_def = self.backend.update_for_command(
AttributeError: 'TFObjectDetectionConfigBuilder' object has no attribute 'update_for_command'
```
If we checked in `ExperimentConfigBuilder.validate` that the backend was of type `BackendConfig`, this wouldn't have happened.

**Comment by simonkassel** [comment]
Am checking whether self.config.backend is a subclass of class Backend?

**Comment by lewfish** [comment]
Note: I corrected `Backend` to be `BackendConfig` in the above description.

I think this answers your question, but if not let me know.

**Comment by lossyrob** [comment]
In this specific case, if the validate command checked that 

```python
if not isinstance(self.config['backend'] , rastervision.backend.BackendConfig):
  raise (Whatever the Validation exception is)
```

Then it would have caught it earlier. The code I'm referencing would be here: https://github.com/azavea/raster-vision/blob/develop/rastervision/experiment/experiment_config.py#L164-L172

You're checking for a `BackendConfig`, not a `Backend` - this is dealing with the Configs and ConfigBuilders, not  the entities.

And be sure to use `isinstance` instead of `type(thing) == (something)`: https://stackoverflow.com/questions/1549801/what-are-the-differences-between-type-and-isinstance

**Comment by simonkassel** [comment]
yeah, here's what i had

```python
backend = self.config.get('backend')
if not issubclass(type(backend), BackendConfig):
    raise rv.ConfigError('Call "build()" on the backend.')
```

**Comment by lossyrob** [comment]
@simonkassel to be clear, this issue is for checking _all_ types in _all_ validation methods - the example given was an example of the type of check.

**Comment by simonkassel** [comment]
yeah, if I understand it correctly, basically if a validate method checks that it has been set, I should check to ensure the type is correct. Is that right?

**Comment by lewfish** [comment]
> @lossyrob yeah, if I understand it correctly, basically if a validate method checks that it has been set, I should check to ensure the type is correct. Is that right?

that's right.
