### ISSUE TITLE
TF requires unsigned 8 bit values

### ISSUE THREAD

**Issue by SFrav** [azavea/raster-vision#546]
Is there a way around the TF requirement of 8 bit values? There will be a bit of a loss in resolution for some instruments.

**Comment by lossyrob** [comment]
We're very interested in this as well, and will be exploring ways to utilize non-byte data, as well as multispectral data. For now, we're restricted to the limits of the  backends we are using. The one backend that does not have this issue is the `rv.KERAS_CLASSIFICATION`, for chip  classification, which can work with N bands and non-byte imagery.

**Comment by lossyrob** [comment]
We actually implemented a custom FCN for semantic segmentation in Keras a while back, and that's in an old tag https://github.com/azavea/raster-vision/tree/old-semseg-tagging/src/rastervision/semseg. This got refactored out, but it's probably worth bringing back into the fold as an alternate backend to  TF DeepLab. This could be on the roadmap, but unclear when it would get prioritized - but would be great to have an external contribution for!
