### ISSUE TITLE
Downloading of files for different runs can not happen when needed

### ISSUE THREAD

**Issue by lossyrob** [azavea/raster-vision#57]
In `download_dataset`, the code checks if the data directory is there, and if not makes it and downloads data. If it is, it considered the data already downloaded. For machines that are being reused in the ECS cluster, it could run multiple trainings. If the one run needs different files from the other, then it can skip downloading important data. We should check for the existence of the files at a per file level (which presents a slight challenge because zip files are deleted for good reason).

**Comment by lewfish** [comment]
We have a job that failed multiple times. In the log https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/batch/job;stream=tagging-6_30_17-dense121_dropout_1/c07db551-573c-4b4c-8dba-4c19ec03bb90/a2768b97-eaea-488a-a669-7edd88c22ed0, I noticed that this line https://github.com/azavea/raster-vision/blob/develop/src/rastervision/common/data/generators.py#L95 is getting called. That should only happen if the channel stats file is missing, which suggests that the data is not on the instance when it's supposed to be there. I suspect that this is being caused by this issue.
