### ISSUE TITLE
I predict own tif files I get an error

### ISSUE THREAD

**Issue by zhan520** [azavea/raster-vision#613]
![image](https://user-images.githubusercontent.com/12770958/49682135-bec97d80-fae9-11e8-8bea-e964b9ef8bbd.png)
I don't know what do I have to do

**Comment by lewfish** [comment]
I think this is because your test image has a different number of channels than the images you trained on. The cowc-potsdam model was trained on 4-band imagery using channels [3, 0, 1] and it's trying to read band 3 when it doesn't exist. To get around this, you should use the `--channel-order` option for the `predict` command.
