### ISSUE TITLE
Splitting chips (rather than scenes) into train/val/test sets

### ISSUE THREAD

**Issue by busycalibrating** [azavea/raster-vision#684]
I've dug through the source code (`rv.object_detection`, `rb.tf_deeplab`, `rv.geotiff_source`, `rv.object_detection_label_source` exhaustively, cursory with other combinations) quite a bit and don't see any support for this natively. I can probably work around this by creating my own Tasks or Backends, but I'm wondering if I overlooked any already existing features that allow this?

**Comment by lossyrob** [comment]
Hey @busycalibrating, I'd like to get a better sense of what you're trying to do and potential ways to solve it. Would chatting about this on Gitter make the most sense? I'd have some time 4pm EST today to chat if you're able to join then, it might be quicker to talk in real time.  Otherwise I'll post questions on this issue later.

**Comment by busycalibrating** [comment]
@lossyrob I should be available - I'll try to drop in then. Thanks a lot!

**Comment by lewfish** [comment]
To summarize what was discussed in the Gitter channel, the main reasons we put entire scenes into splits is that it allows us to predict and evaluate over entire scenes. This allows us to view predictions as contiguous areas on a map and evaluate the ability to handle inter-chip seams. 

We could get some of the advantage of splitting over chips without a drastic modification to the system by splitting scenes into a larger number of smaller scenes. You could just write a script that takes a list of scenes and generates new (smaller) GeoTIFFs, but that would waste disk space and externalize the problem. We could also take a scene and repeat it many times in the dataset, each time with a different AOI which covers a subset of the image. The problem is that the predict command will still predict over the entire image in each scene, which would waste a lot time. (The eval command however only compares the parts of the scenes that are within the AOIs.) I think the chip command would also download the image file over and over, although there's probably a way of caching it. 

One solution that comes to mind is a special kind of AOI that defines a single rectangle over the image. You could call it a "virtual extent". The combination of a virtual extent and an image in a scene would define a sub-scene. RV could then use the virtual extent to only download and operate over that part of the image.

**Comment by AdeelH** [comment]
This is now possible via #1030
