### ISSUE TITLE
fail install on windows 10 with python 3.7 64bits

### ISSUE THREAD

**Issue by geopamplona** [azavea/raster-vision#841]
I have next error, when try install rastervision from VisualStudio or command line in Windows 10:

Usuario

> /c/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64
> $ ./python -m pip install rastervision --user --no-cache-dir
> Collecting rastervision
>   Downloading https://files.pythonhosted.org/packages/08/e7/353df3b3cb7a8caab68702d8d72b2ae4c826b54d5e4a4213212d61fb0d3e/rastervision-0.10.0-py3-none-any.whl (396kB)
> ERROR: Could not install packages due to an EnvironmentError: [WinError 267] El nombre del directorio no es v▒lido: 'C:\\Users\\Usuario\\AppData\\Local\\Temp\\pip-install-fpxxp1qz\\rastervision\\rastervision/command/aux'

I have tried different things but I have not been able to install it on windows. I have also tried version 0.9.0 and neither
I know that it is not a priority for rastervision to offer support on windows, however for me it is important to do small tests locally.
Thanks

**Comment by Chuan1997** [comment]
same problem! hope someone can help solve the problem

**Comment by Tobias314** [comment]
Seems like "aux" is a reserved name under windows. So the rastervision.command.aux package (rastervision/command/aux) should probably be renamed into something other than "aux".

**Comment by HallMattD** [comment]
Same here: 

`(arcgispro-py3-clone) C:\Users\MDHall\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone>pip install rastervision
Collecting rastervision
  Using cached https://files.pythonhosted.org/packages/08/e7/353df3b3cb7a8caab68702d8d72b2ae4c826b54d5e4a4213212d61fb0d3e/rastervision-0.10.0-py3-none-any.whl
ERROR: Could not install packages due to an EnvironmentError: [WinError 267] The directory name is invalid: 'C:\\Users\\MDHall\\AppData\\Local\\Temp\\pip-install-f93ib626\\rastervision\\rastervision/command/aux'`

Windows 10, Python 3.6.9

**Comment by lewfish** [comment]
RV2 doesn't have an `aux` package so that should fix it.

**Comment by mikeyEcology** [comment]
I'm getting the same error and I just cloned the repository today. Is there somewhere else I should be looking for `RV2`? I'm using Python 3.8.3 and I'm stuck using Windows: `pip install rastervision`
> pip install rastervision
Collecting rastervision
  Using cached rastervision-0.11.0-py3-none-any.whl (586 kB)
ERROR: Could not install packages due to an EnvironmentError: [WinError 267] The directory name is invalid: 'C:\\...\\AppData\\Local\\Temp\\pip-install-vhu8z2dp\\rastervision\\rastervision/command/aux'
