### ISSUE TITLE
README.md setup instructions conflict with available code

### ISSUE THREAD

**Issue by aaroncnb** [azavea/raster-vision#862]
Hi!

Upon following the setup instructions, I have a problem with this part:

> From within the project root, execute the following commands.

```
./scripts/setup
```

There appears to be no script called `setup` in the <project-root-foler>/scripts directory.

**Comment by lewfish** [comment]
Hello! Where did you find these instructions? It looks like they must be out of date because indeed there is no `./scripts/setup`. If you're using the docs site, make sure to use the latest version 0.10 (https://docs.rastervision.io/en/0.10/index.html) and if you're looking at the RV readme use the master branch at https://github.com/azavea/raster-vision
